# Generated by Django 5.1.4 on 2025-01-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0002_mangoreviewmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangomodels',
            name='image',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
