# Generated by Django 5.1.4 on 2025-01-25 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mango', '0003_alter_mangomodels_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('delivery_status', models.CharField(choices=[('Pending', 'Pending'), ('Proceccing', 'Proceccing'), ('Completed', 'Completed'), ('Cancel', 'Cancel')], default='Pending', max_length=100)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.IntegerField(blank=True, default=0, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('deliveryPostCode', models.IntegerField(blank=True, null=True)),
                ('deliveryPhone', models.IntegerField(blank=True, null=True)),
                ('mango', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mango.mangomodels')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
